`ifndef DEFINE_STATE

// This defines the states
// Mil1 states
typedef enum logic [5:0] {
	S_FSM_IDLE,
	S_LOAD_READ,
	S_INTI_FSM,
	S_INTI_FSM_1,
	S_INTI_INT_U,
	S_INTI_INT_U_1,
    S_INTI_INT_V,
	S_INTI_INT_V_1,
	S_INTI_INTERPOLATION,
	S_INTI_INTERPOLATION_1,
	S_INTI_INTERPOLATION_2,
	S_INTI_INTERPOLATION_3,
	S_INTI_INTERPOLATION_4,
	S_INTI_INTERPOLATION_5,
	S_INTI_INTERPOLATION_6,
	S_CYC_CSC_INT,
	S_CYC_CSC_INT_1,
	S_CYC_CSC_INT_2,
	S_CYC_CSC_INT_3,
	S_CYC_CSC_INT_4,
	S_CYC_CSC_INT_5,
	S_CYC_CSC_INT_6,
	S_CYC_TWO_CSC_INT,
	S_CYC_TWO_CSC_INT_1,
	S_CYC_TWO_CSC_INT_2,
	S_CYC_TWO_CSC_INT_3,
	S_CYC_TWO_CSC_INT_4,
	S_CYC_TWO_CSC_INT_5,
	S_CYC_TWO_CSC_INT_6
	
} FSM_state_type;

// Mil2 States
typedef enum logic [6:0] {
	S_FSM2_IDLE,
	DP_RAM_LOAD_1,
	DP_RAM_LOAD_2,
	DP_RAM_LOAD_3,
	DP_RAM_LOAD_4,
	DP_RAM_LOAD_5,
	DP_RAM_LOAD_6,
	DP_RAM_LOAD_7,
	DP_RAM_LOAD_8,
	DP_RAM_LOAD_9,
	DP_RAM_LOAD_10,
	DP_RAM_LOAD_11,
	DP_RAM_LOAD_12,
	DP_RAM_LOAD_13,
	DP_RAM_LOAD_14,
	DP_RAM_LOAD_15,
	DP_RAM_LOAD_16,
	DP_RAM_LOAD_17,
	DP_RAM_LOAD_18,
	DP_RAM_LOAD_19,
	DP_RAM_LOAD_20,
	DP_RAM_LOAD_21,
	DP_RAM_LOAD_22,
	DP_RAM_LOAD_23,
	DP_RAM_LOAD_24,
	DP_RAM_LOAD_25,
	DP_RAM_LOAD_26,
	DP_RAM_LOAD_27,
	DP_RAM_LOAD_28,
	DP_RAM_LOAD_29,
	DP_RAM_LOAD_30,
	DP_RAM_LOAD_31,
	DP_RAM_LOAD_32,
	
	S_INIT_ADDR_COUNT,
	S_INIT_ADDR_COUNT_2,
	S_INIT_ADDR_COUNT_3,
	S_INIT_CYC_ADDR_FETCH,
	S_INIT_CYC_ADDR_FETCH_1,
	S_INIT_CYC_FETCH_LEAD_OUT,
	S_INIT_CYC_FETCH_LEAD_OUT_1,
	S_INIT_SC,
	S_dummy,
	S_dummy1,
	S_INTI_CYC_SC,
	S_INTI_SC_1,
	S_CYC_INTI_SC,
	S_CYC_INTI_SC_1,
	S_CYC_INTI_SC_2,
	S_CYC_INTI_SC_3,
	S_CYC_INTI_SC_4,
	S_CYC_INTI_SC_5,
	S_CYC_INTI_SC_6,
	S_CYC_INTI_SC_7,
	S_CYC_INTI_SC_8,
	S_CYC_TWO_INTI_SC,
	S_CYC_TWO_INTI_SC_1,
	S_CYC_TWO_INTI_SC_2,
	S_CYC_TWO_INTI_SC_3,
	S_CYC_TWO_INTI_SC_4,
	S_CYC_TWO_INTI_SC_5,
	S_CYC_TWO_INTI_SC_6,
	S_CYC_TWO_INTI_SC_7,
	S_SC_LEAD_OUT,
	S_SC_LEAD_OUT_1,
	S_FULL_CYC,
	S_FULL_CYC_1,
	S_START_CYC,
	S_START_CYC_1,
	S_START_CYC_2,
	S_START_CYC_3,
	S_START_CYC_4,
	S_START_CYC_5,
	S_START_CYC_6,
	S_START_CYC_7,
	S_START_TWO_CYC,
	S_START_TWO_CYC_1,
	S_START_TWO_CYC_2,
	S_START_TWO_CYC_3,
	S_START_TWO_CYC_4,
	S_START_TWO_CYC_5,
	S_START_TWO_CYC_6,
	S_START_TWO_CYC_7,
	S_CYC_LEAD_IN,
	S_CYC_LEAD_IN_1,
	S_CYC_LEAD_IN_2,
	S_CYC_TWO_CS_8,
	S_CYC_TWO_INTI_CS_8
} FSM2_state_type;


typedef enum logic [2:0] {
	S_IDLE,
	S_M2,
	S_M1,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX
} top_state_type;

typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;

typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

`define DEFINE_STATE 1
`endif
